[package]
name = "dbus-async"
version = "1.1.0"
authors = ["LinkTed <link.ted@mailbox.org>"]
description = "Asynchronous DBus library"
readme = "README.md"
keywords = ["dbus", "async"]
license = "BSD-3-Clause"
edition = "2018"
include = [
    "src/**/*.rs",
    "tests/*.rs",
    "examples/*.rs", 
    "Cargo.toml",
    "README.md",
    "LICENSE"
    ]
repository = "https://github.com/LinkTed/dbus-async"
categories = ["asynchronous"]

[badges]
travis-ci = { repository = "LinkTed/doh-client" }

[dependencies]
log = "0.4.11"
lazy_static = "1.4.0"
futures = "0.3.7"
dbus-message-parser = "3.0.1"
hex = "0.4.2"
bytes = "0.6.0"
regex = "1.4.2"
lru = "0.6.1"
libc = "0.2.80"
bitflags = "1.2.1"
retain_mut = "0.1.1"
async-trait = "0.1.41"

[dependencies.tokio]
version = "0.3.3"
features = ["net", "io-util"]

[dev-dependencies.tokio]
version = "0.3.3"
features = ["rt-multi-thread", "macros"]
